### ISSUE TITLE
Why this project needs a custom ObjectId object?

### ISSUE THREAD

**Issue by matheuslima** [michel-kraemer/bson4jackson#69]
I cannot understand why this plugins needs to use a own ObjectId object and I also don't understand why it haven't a factory method to instantiate the ObjectiId. Actually I create new ObjectId instances using the ```org.bson.types.ObjectId``` and not seems very much convenient.

**Comment by michel-kraemer** [comment]
The project implements the BSON specification [1]. BSON specifies an `ObjectId` element, that's why we need an `ObjectId` class in this project, just like any other BSON parser or generator.

The reason we are not using `org.bson.types.ObjectId` is that we don't want to have a dependency from bson4jackson to a MongoDB library (which itself already contains a pretty decent BSON parser by the way).

If you want to use bson4jackson with MongoDB please have a look at Jongo [2]. This project defines Jackson serializers and deserializers for all MongoDB types and uses bson4jackson internally.

I hope this helps. Let me know if you need anything else.

Cheers,
Michel

[1] http://bsonspec.org/
[2] http://jongo.org/
