### ISSUE TITLE
ObjectId mismatch

### ISSUE THREAD

**Issue by PSchmitzHeuBoe** [michel-kraemer/bson4jackson#73]
There is a difference in de.undercouch.bson4jackson.types.ObjectId and org.bson.types.ObjectId (Version 3.4.2).  org.bson.types.ObjectId holds an additional processIdentifier.

**Comment by craffael** [comment]
Same problem here. I could create a patch and change the de.undercouch.bson4jackson.types.ObjectId to the format of org.bson.types.ObjectId...

**Comment by PSchmitzHeuBoe** [comment]
Hi craffael,

I am very interested in your solution. Is it possible to create a pull request?

Kind regards,
Peter Schmitz

**Comment by craffael** [comment]
Well after looking at it in detail, it seems that the two formats are indeed compatible. Checkout the test objectId() in `bson4jackson/src/test/java/de/undercouch/bson4jackson/serializers/BsonSerializersTest.java` which shows exactly how the fields correspond to each other.

So to create a de.undercouch.bson4jackson.types.ObjectId from a org.bson.types.ObjectId, just use
```java
org.bson.types.ObjectId bsonObjectId = new org.bson.types.ObjectId();
de.undercouch.bson4jackson.types.ObjectId jacksonObjectId = new de.undercouch.bson4jackson.types.ObjectId(bsonObjectId.getTimeSecond(), bsonObjectId.getMachine(), bsonObjectId.getInc());
```

Of course it would also be possible to support org.bson.types.ObjectId directly in bson4jackson, but this would induce another dependency and I think @michel-kraemer wanted to avoid this, so he created de.undercouch.bson4jackson.types.ObjectId.

**Comment by michel-kraemer** [comment]
@craffael Your observation is correct. bson4jackson is very generic and does not provide specific support for MongoDB or the types from the `org.bson` package. The decision to create custom types was made at a time when `org.bson` was still in the MongoDB java driver and not in its own jar. Note that I'm currently working on bson4jackson 3.0.0 (see the 3.0.0 branch) which will use the types from `org.bson` directly. It will take some time until this version will be released because I want to sync the release with Jackson 3.0.0 - and I don't know yet when this will happen.

In the meantime you may use one of the following libraries which include bson4jackson and target MongoDB specifically:

Jongo:
http://jongo.org/

and its implementation for `ObjectId`s:
https://github.com/bguerout/jongo/blob/master/src/main/java/org/jongo/marshall/jackson/oid/ObjectIdSerializer.java

MongoJack:
http://mongojack.org/

and its implementation for `ObjectId`s:
https://github.com/mongojack/mongojack/blob/master/src/main/java/org/mongojack/internal/ObjectIdSerializer.java

I hope this helps. I'm closing this issue. Let me know if you need more help and feel free to reopen it.
